/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-03-15 20:48:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;

public final class jsp_005ftest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1458074885901L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1458074884175L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; UTF-8\">\r\n");
      out.write(" \r\n");
      out.write(" \t<script type=\"text/javascript\" src=\"yoxview/yoxview-init.js\"></script>\r\n");
      out.write("  \t<script type=\"text/javascript\" src=\"yoxview/lang/bg.js\"></script>\r\n");
      out.write("\t<link href = \"css/styles.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href = \"css/bootstrap.min.css\" rel = \"stylesheet\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://jqueryvalidation.org/files/dist/jquery.validate.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://jqueryvalidation.org/files/dist/additional-methods.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class = \"container\">\r\n");
      out.write("\t\t<nav class = \"navbar navbar-default\" style=\"background-color:white\" role = \"navigation\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<ul class = \"nav nav-justified nav-pills\">\r\n");
      out.write("\t\t\t\t \t  \t<li class=\"active\"><a href=\"#\" >Автомобили</a></li>\r\n");
      out.write("\t\t\t\t \t  \t<li><a href=\"#\" >Джипове</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" >Бусове</a></li>\r\n");
      out.write("\t\t\t\t \t\t<li><a href=\"#\" >Камиони</a></li>\r\n");
      out.write("\t\t\t\t \t\t<li><a href=\"#\" >Мотоциклети</a></li>\r\n");
      out.write("\t\t\t\t \t\t<li><a href=\"#\" >Селскостопански</a></li>\r\n");
      out.write("\t\t\t\t  \t \t<li><a href=\"#\" >Индустриални</a></li>\r\n");
      out.write("\t\t\t\t  \t\t<li><a href=\"#\" >Кари</a></li>\r\n");
      out.write("\t\t\t\t   \t\t<li><a href=\"#\" >Каравани</a> </li>\r\n");
      out.write("\t\t\t\t   \t\t<li><a href=\"#\" >Ремаркета</a></li>\r\n");
      out.write("\t\t\t\t   \t\t<li><a href=\"#\" >Велосипеди</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\t\r\n");
      out.write("\t\t\t\t<div class = \"col-md-5\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style = \"float:right\"> <img alt = \"Logo\" src=\"images/logo.png\"> </a>\r\n");
      out.write("\t\t \t\t</div>\r\n");
      out.write("\t\t \t\t<div class=\"col-md-7\" style=\"margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<form action=\"Login\" method=\"POST\" class=\"row navbar-form navbar-left form-inline\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t\t<input\ttype=\"email\" name=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Е-мейл\" required\r\n");
      out.write("\t\t\t\t\t\t\t\toninvalid=\"this.setCustomValidity('Моля въведете валиден е-мейл.')\" oninput=\"setCustomValidity('')\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"pass\" id=\"pass\" class=\"form-control\"  placeholder=\"Парола\" required\r\n");
      out.write("\t\t\t\t\t\t\t\toninvalid=\"this.setCustomValidity('Моля въведете парола.')\" oninput=\"setCustomValidity('')\" >\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-success form-control\" value=\"Вход\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"margin-left: 0px; margin-top:5px;\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"row nav navbar-left nav-pills\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"main.html\">Начало</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a href=\"search.html\">Търсене</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"publish.html\">Публикуване</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"http://automedia.investor.bg/\">Новини</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Форум</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Контакти</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Моето мобиле</a>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t  \t\t</div>\r\n");
      out.write("\t\t  \t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\t<div class=\"container footer-font\">\t\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>За нас</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"#\"> Условия за ползване</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"#\"> Поверителност</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"#\">\tКонтакти</a></p></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>Kонтакти</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p><i class=\"glyphicon glyphicon-map-marker\"></i> <strong>Адрес:</strong> София 1404, бул. “България” №69, ет.14, Infinity Tower</p></li>\r\n");
      out.write("\t\t\t\t\t<li><p><i class=\"glyphicon glyphicon-envelope\"></i> <strong>Email:</strong> hakan.hyusen94@gmail.com </p></li>\r\n");
      out.write("\t\t\t\t\t<li><p><i class=\"glyphicon glyphicon-globe\"></i> <strong>Website:</strong> <a href=\"#\">www.jiguili.bg</a></p></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>Друго</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2; <a href=\"#\"> Форум</a></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2; <a href=\"#\"> FAQ's</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2; <a href=\"#\"> Помощ</a></p></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>Посетете също</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"http://automedia.investor.bg/\"> Automedia.bg</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"http://www.mobile.bg/\"> Mobile.bg</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"http://www.topgear.bg/\"> Topgear.bg</a></p></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<p style=\"text-align: center;\"> © Copyright 2016. All rights reserved.</p>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
