/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-03-17 16:13:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.runtime.JspWriterImpl;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


						public String funct(String s){
							if(s.equals("/search.jsp") || s.equals("/advert.jsp") || s.equals("/results.jsp")){
								return "search";
							}
							if(s.equals("/main.jsp")){
								return "main";
							}
							if(s.equals("/publish.jsp")){
								return "publish";
							}
							return null;
						}
					
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1458160846424L));
    _jspx_dependants.put("jar:file:/C:/Users/User/Desktop/Java/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Mobile.bg/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1458149494968L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1458229792255L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.jasper.runtime.JspWriterImpl");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=en>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Mobile.bg - Пазарът за автомобили в България.</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE = edge\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width = device-width, initial-scale = 1\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"http://jqueryvalidation.org/files/dist/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"http://jqueryvalidation.org/files/dist/additional-methods.min.js\"></script>\r\n");
      out.write("<script src=\"js/validation.js\"></script>\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-default\" style=\"background-color: white\"\r\n");
      out.write("\t\t\trole=\"navigation\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-justified nav-pills\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">Автомобили</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Джипове</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Бусове</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Камиони</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Мотоциклети</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Селскостопански</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Индустриални</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Кари</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Каравани</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Ремаркета</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Велосипеди</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"float: right\"> <img alt=\"Logo\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/logo.png\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-7\" style=\"margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          //  c:when
          org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /header.jsp(34,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f0.setTest( (!session.isNew() && session.getAttribute("userId")!=null ) );
          int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
          if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t<div class = \"row\" style=\"margin-left:-20px; font-size:20px; margin-bottom: 15px; margin-top: 15px;\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-user\"></span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              out.print( session.getAttribute("firstName") + " " + session.getAttribute("lastName") );
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4\" >\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-envelope\"></span> Съобщения\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<a href=\"./Logout\" style=\"color: #c40005;\"><span class=\"glyphicon glyphicon-log-out\"></span> Изход </a>\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
          out.write("\t\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return;
          out.write(" \r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t$( document ).ready(function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar currentPage = \"");
      out.print( funct(request.getServletPath()) );
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t$('#' + currentPage).addClass('active');\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"margin-left: 0px; font-size:18px; margin-top: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"row nav navbar-left nav-pills\">\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"main\"><a href=\"main.jsp\">Начало</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"search\"><a href=\"search.jsp\">Търсене</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"publish\"><a href=\"publish.jsp\">Публикуване</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"news\"><a href=\"http://automedia.investor.bg/\">Новини</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"forum\"><a href=\"#\">Форум</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"contacts\"><a href=\"#\">Контакти</a>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<!-- Main body -->\r\n");
      out.write("<div class=\"container\" style=\"background-color: white\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<!-- New search column -->\r\n");
      out.write("\t\t<form id=\"searchForm\" action=\"Search\" method=\"post\" target=\"_blank\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<h3 class=\"panel-title\">Търсене</h3>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\" for=\"category\"> Основна категория</label> \r\n");
      out.write("\t\t\t\t\t\t<select id=\"category\" name=\"category\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"car\" selected>Автомобили</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"jeep\">Джипове</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"bus\">Бусове</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"truck\">Камиони</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"moto\">Мотоциклети</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"аgro\">Селскостопански</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"industr\">Индустриални</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"carry\">Кари</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"caravan\">Каравани</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"trailer\">Ремаркета</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"bikes\">Велосипеди</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row search-form\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label\" for=\"brand\"> Марка</label> <select\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"brand\" name=\"brand\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"all\">Всички</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"asd\">Honda</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label\" for=\"model\"> Модел</label> <select\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"model\" name=\"model\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"all\">Всички</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"civic\">Civic</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\" for=\"еngine\"> Двигател</label> <select\r\n");
      out.write("\t\t\t\t\t\t\tid=\"еngine\" name=\"еngine\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"all\">Всички</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"petrol\">Бензинов</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"diesel\">Дизелов</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"electric\">Електрически</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"hybrid\">Хибриден</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\" for=\"gearbox\"> Скоростна кутия</label>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"gearbox\" name=\"gearbox\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"all\">Всички</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"auto\">Автоматична</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"semiauto\">Полуавтоматична</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"manual\">Ръчна</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\"> Цена</label> <br>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"minPrice\" name=\"minPrice\" type=\"number\" min=\"0\" placeholder=\"От\" \r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control input-md\" style=\"width:49%; display: inline;\"\r\n");
      out.write("\t\t\t\t\t\t\toninput=\"setCustomValidity('')\" oninvalid=\"setCustomValidity('Въведете цена по-голяма от 0.')\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"maxPrice\" name=\"maxPrice\" type=\"number\" min=\"#minPrice\" placeholder=\"До\" \r\n");
      out.write("\t\t\t\t\t\t    class=\"form-control input-md\" style=\"width:49%;  display: inline;\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\">Година</label> <br>\r\n");
      out.write("\t\t\t\t\t\t<input id=\"minYear\" name=\"minYear\" type=\"number\" min=\"1950\" max=\"2016\" placeholder=\"От\" \r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"1950\" class=\"form-control input-md\" style=\"width:49%; display: inline;\"\r\n");
      out.write("\t\t\t\t\t\t\toninput=\"setCustomValidity('')\" oninvalid=\"setCustomValidity('Въведете валидна година.')\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"maxYear\" name=\"maxYear\" type=\"number\" min=\"1950\" max=\"2016\" placeholder=\"До\" \r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"2016\" class=\"form-control input-md\" style=\"width:49%;  display: inline;\"\r\n");
      out.write("\t\t\t\t\t\t\toninput=\"setCustomValidity('')\" oninvalid=\"setCustomValidity('Въведете валидна година.')\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"search-form2\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\" for=\"condition\">Състояние: </label>\r\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox-inline\" for=\"new\"> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"condition\" id=\"new\" value=\"new\" checked=\"checked\"> Нов </label> \r\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox-inline\" for=\"used\"> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"condition\" id=\"used\" value=\"used\"> Употребяван </label> \r\n");
      out.write("\t\t\t\t\t\t<label class=\"checkbox-inline\" for=\"parts\"> \r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"checkbox\" name=\"condition\" id=\"parts\" value=\"parts\"> На части </label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"search-form2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" form=\"searchForm\" class=\"btn btn-info btn-block\" value = \"Т Ъ Р С Е Н Е\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- News column -->\r\n");
      out.write("\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"http://automedia.investor.bg/\"\tstyle=\"text-decoration: none\">Новини от Automedia.bg</a>\r\n");
      out.write("\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"myCarousel\" class=\"carousel slide\">\r\n");
      out.write("\t\t\t\t\t<!-- Carousel indicators -->\r\n");
      out.write("\t\t\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"\t\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Carousel items -->\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-inner\" style=\"background-color: black\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"http://automedia.investor.bg/a/0-nachalo/26848-honda-spria-noviia-civic-zaradi-problem-s-motora/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"http://automedia.investor.bg/images/assets/1454565973-01-1.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"First slide\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"http://automedia.investor.bg/a/0-nachalo/26848-honda-spria-noviia-civic-zaradi-problem-s-motora/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tHonda спря новия Civic заради проблем с мотора</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"http://automedia.investor.bg/a/0-nachalo/26817-poiavi-se-nov-konkurent-na-tesla/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"http://automedia.investor.bg/images/assets/1454398260-763190-image-numerique-tomahawk-sera-presente.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Second slide\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"http://automedia.investor.bg/a/0-nachalo/26817-poiavi-se-nov-konkurent-na-tesla/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tПояви се нов конкурент на Tesla</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"http://automedia.investor.bg/a/0-nachalo/26830-evropeicite-izbraha-honda-za-1/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"http://automedia.investor.bg/images/assets/1454406907-RTXY02V.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Third slide\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-caption\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"http://automedia.investor.bg/a/0-nachalo/26830-evropeicite-izbraha-honda-za-1/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tЕвропейците избраха Honda за №1</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Carousel nav -->\r\n");
      out.write("\t\t\t\t\t<a class=\"carousel-control left\" href=\"#myCarousel\"\r\n");
      out.write("\t\t\t\t\t\tdata-slide=\"prev\">&lsaquo;</a> <a class=\"carousel-control right\"\r\n");
      out.write("\t\t\t\t\t\thref=\"#myCarousel\" data-slide=\"next\">&rsaquo;</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel-footer\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-primary\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"panel-title\">Регистрация</h3>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"reg-panel\">\r\n");
      out.write("\t\t\t\t\t<form id=\"regForm\" action=\"Registration\" method=\"post\" target=\"_blank\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\" style=\"padding-right: 2px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"first_name\" id=\"first_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Име\" class=\"form-control input-md\" required>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-6\" style=\"padding-left: 2px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"last_name\" id=\"last_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Фамилия\" class=\"form-control input-md\" required>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"region\" id=\"region\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Регион\" required>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" id=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"E-мейл\"  required>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"Парола\"  required>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"passwordConfirm\" id=\"passwordConfirm\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control required equalTo'#password'\" placeholder=\"Потвърждение\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\tПри натискане на <strong class=\"label label-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\tРегистрация</strong> вие се съгласявате с нашите <a href=\"#\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"color: #337ab7\" data-toggle=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-target=\"#t_and_c_m\">Условия</a>.\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" form=\"regForm\" value=\"Регистрация\" class=\"btn btn-info btn-block\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\t<div class=\"container footer-font\" style=>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>За нас</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"#\"> Условия за ползване</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"#\"> Поверителност</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"#\"> Контакти</a></p></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>Kонтакти</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p><i class=\"glyphicon glyphicon-map-marker\"></i> <strong>Адрес:</strong>\r\n");
      out.write("\t\t\t\t\t\tСофия 1404, бул. “България” №69, ет.14, Infinity Tower</p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><p><i class=\"glyphicon glyphicon-envelope\"></i> \r\n");
      out.write("\t\t\t\t\t\t<strong>Email:</strong>hakan.hyusen94@gmail.com</p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><p><i class=\"glyphicon glyphicon-globe\"></i> \r\n");
      out.write("\t\t\t\t\t\t<strong>Website:</strong><a href=\"#\">www.jiguili.bg</a></p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>Друго</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p>\t&#x27a2; <a href=\"#\"> Форум</a></li>\r\n");
      out.write("\t\t\t\t\t<li><p> &#x27a2; <a href=\"#\"> FAQ's</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>\t&#x27a2; <a href=\"#\"> Помощ</a></p></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>Посетете също</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"http://automedia.investor.bg/\"> Automedia.bg</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"http://www.mobile.bg/\"> Mobile.bg</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"http://www.topgear.bg/\"> Topgear.bg</a></p></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<p style=\"text-align: center;\">© Copyright 2016. All rights reserved.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<form action=\"Login\" method=\"POST\" class=\"row navbar-form navbar-left form-inline\" target=\"_blank\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Е-мейл\" required\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\toninvalid=\"this.setCustomValidity('Моля въведете валиден е-мейл.')\" oninput=\"setCustomValidity('')\"> \r\n");
        out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"pass\" id=\"pass\" class=\"form-control\" placeholder=\"Парола\" required\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\toninvalid=\"this.setCustomValidity('Моля въведете парола.')\" oninput=\"setCustomValidity('')\"> \r\n");
        out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-success form-control\" value=\"Вход\">\r\n");
        out.write("\t\t\t\t\t\t\t\t</form>\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
