/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-03-17 16:02:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.jasper.runtime.JspWriterImpl;

public final class publish_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


						public String funct(String s){
							if(s.equals("/search.jsp") || s.equals("/advert.jsp") || s.equals("/results.jsp")){
								return "search";
							}
							if(s.equals("/main.jsp")){
								return "main";
							}
							if(s.equals("/publish.jsp")){
								return "publish";
							}
							return null;
						}
					
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1458160846424L));
    _jspx_dependants.put("jar:file:/C:/Users/User/Desktop/Java/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Mobile.bg/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153374282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1458149494968L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1458229792255L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.jasper.runtime.JspWriterImpl");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=en>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Mobile.bg - Пазарът за автомобили в България.</title>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE = edge\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width = device-width, initial-scale = 1\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"http://jqueryvalidation.org/files/dist/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"http://jqueryvalidation.org/files/dist/additional-methods.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-default\" style=\"background-color: white\"\r\n");
      out.write("\t\t\trole=\"navigation\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-justified nav-pills\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"#\">Автомобили</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Джипове</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Бусове</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Камиони</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Мотоциклети</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Селскостопански</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Индустриални</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Кари</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Каравани</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Ремаркета</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Велосипеди</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" style=\"float: right\"> <img alt=\"Logo\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/logo.png\">\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-7\" style=\"margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          //  c:when
          org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /header.jsp(34,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f0.setTest( (!session.isNew() && session.getAttribute("userId")!=null ) );
          int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
          if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t<div class = \"row\" style=\"margin-left:-20px; font-size:20px; margin-bottom: 15px; margin-top: 15px;\">\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-user\"></span>\r\n");
              out.write("\t\t\t\t\t\t\t\t\t");
              out.print( session.getAttribute("firstName") + " " + session.getAttribute("lastName") );
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4\" >\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-envelope\"></span> Съобщения\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<a href=\"./Logout\" style=\"color: #c40005;\"><span class=\"glyphicon glyphicon-log-out\"></span> Изход </a>\r\n");
              out.write("\t\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t\t</div>\r\n");
              out.write("\t\t\t\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
          out.write("\t\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return;
          out.write(" \r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t$( document ).ready(function() {\r\n");
      out.write("\t\t\t\t\t\t\tvar currentPage = \"");
      out.print( funct(request.getServletPath()) );
      out.write("\";\r\n");
      out.write("\t\t\t\t\t\t\t$('#' + currentPage).addClass('active');\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row\" style=\"margin-left: 0px; font-size:18px; margin-top: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"row nav navbar-left nav-pills\">\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"main\"><a href=\"main.jsp\">Начало</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"search\"><a href=\"search.jsp\">Търсене</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"publish\"><a href=\"publish.jsp\">Публикуване</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"news\"><a href=\"http://automedia.investor.bg/\">Новини</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"forum\"><a href=\"#\">Форум</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"contacts\"><a href=\"#\">Контакти</a>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/vehicleDynamicSelect.js\"></script>\r\n");
      out.write("<script src=\"js/regionDynamicSelect.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form id=\"publishForm\" action=\"PublishVehicle\" method=\"post\" target=\"_blank\">\r\n");
      out.write("\t<div class=\"container panel-heading panel-primary\" style=\"border-bottom: 1px solid #ccc; padding-bottom: 25px\">\r\n");
      out.write("\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t<h4 class=\"font\">Публикуване на нов автомобил</h4>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"panel-primary\" style=\"padding-top: 20px\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"category\">Основна категория</label> \r\n");
      out.write("\t\t\t\t\t<select id=\"category\" name=\"category\" class=\"form-control\" required \r\n");
      out.write("\t\t\t\t\t\toninput=\"setCustomValidity('')\" oninvalid=\"setCustomValidity('Моля изберете категория')\">\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row search-form\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\" for=\"brand\">Марка</label> \r\n");
      out.write("\t\t\t\t\t\t<select id=\"brand\" name=\"brand\" class=\"form-control\" required \r\n");
      out.write("\t\t\t\t\t\t\toninput = \"setCustomValidity('')\" oninvalid=\"setCustomValidity('Моля задайте марка.')\">\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\" for=\"model\">Модел</label> \r\n");
      out.write("\t\t\t\t\t\t<select id=\"model\" name=\"model\" class=\"form-control\" required \r\n");
      out.write("\t\t\t\t\t\t\toninput = \"setCustomValidity('')\" oninvalid=\"setCustomValidity('Моля задайте модел.')\">\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"engine\">Двигател</label> \r\n");
      out.write("\t\t\t\t\t<select id=\"engine\" name=\"engine\" class=\"form-control\" \r\n");
      out.write("\t\t\t\t\t\trequired oninput=\"setCustomValidity('')\"\r\n");
      out.write("\t\t\t\t\t\toninvalid=\"setCustomValidity('Моля изберете тип двигател.')\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"petrol\">Бензинов</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"diesel\">Дизелов</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"electric\">Електрически</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"hybrid\">Хибриден</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"gearbox\" >Скоростна кутия</label>\r\n");
      out.write("\t\t\t\t\t<select id=\"gearbox\" name=\"gearbox\" class=\"form-control\"  \r\n");
      out.write("\t\t\t\t\t\trequired oninput=\"setCustomValidity('')\" \r\n");
      out.write("\t\t\t\t\t\toninvalid=\"setCustomValidity('Моля изберете тип скоростна кутия.')\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\"></option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"auto\">Автоматична</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"semiauto\">Полуавтоматична</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"manual\">Ръчна</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row search-form2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\" for=\"price\">Цена</label> \r\n");
      out.write("\t\t\t\t\t\t<input id=\"price\" name=\"price\" type=\"number\" min=\"0\" placeholder=\"Цена\" \r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control input-md\" required oninput = \"setCustomValidity('')\" \r\n");
      out.write("\t\t\t\t\t\t\toninvalid=\"setCustomValidity('Моля въведете валидна цена.')\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\" for=\"currency\">Валута</label> \r\n");
      out.write("\t\t\t\t\t\t<select id=\"currency\" name=\"currency\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"lv\">лв.</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"usd\">USD</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"euro\">EUR</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-4\" style=\"margin-top: 25px\">\r\n");
      out.write("\t\t\t\t<div class=\"coll-md-12\" >\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"condition\">Състояние: </label> \r\n");
      out.write("\t\t\t\t\t<label class=\"radio-inline\" for=\"new\"> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"condition\" id=\"new\" value=\"new\">Нов\r\n");
      out.write("\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t<label class=\"radio-inline\" for=\"used\"> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"condition\" id=\"used\" value=\"used\" checked>Употребяван\r\n");
      out.write("\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t<label class=\"radio-inline\" for=\"parts\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"condition\" id=\"parts\" value=\"parts\"> На части\r\n");
      out.write("\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label search-form2\" for=\"power\">Мощност\r\n");
      out.write("\t\t\t\t\t\t</label> в конски сили <input id=\"power\" name=\"power\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"Мощност\" class=\"form-control input-md\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label search-form2\" for=\"mileage\">Пробег </label> в километри \r\n");
      out.write("\t\t\t\t\t\t<input id=\"mileage\" name=\"mileage\" type=\"number\" min=\"0\" placeholder=\"Пробег\" required\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control input-md\" oninput=\"setCustomValidity('') \"\r\n");
      out.write("\t\t\t\t\t\t\toninvalid=\"setCustomValidity('Моля въведете пробег(число по-голямо от 0)')\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<label class=\"control-label search-form2\" for=\"month\">Дата на производство</label>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<select id=\"month\" name=\"month\" class=\"form-control\" required \r\n");
      out.write("\t\t\t\t\t\t\toninvalid=\"setCustomValidity('Моля въведете месец.')\" oninput=\"setCustomValidity('')\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\" disabled selected>месец</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"janury\">Януари</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"february\">Февруари</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"march\">Март</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"april\">Април</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"may\">Май</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"june\">Юни</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"july\">Юли</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"august\">Август</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"september\">Септември</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"october\">Октомври</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"november\">Ноември</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"december\">Декември</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<input id=\"year\" name=\"year\" type=\"number\" min=\"1950\" max=\"2016\" placeholder=\"Година\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"2016\" class=\"form-control input-md\" required oninput = \"setCustomValidity('')\" \r\n");
      out.write("\t\t\t\t\t\t\toninvalid=\"setCustomValidity('Моля въведете валидна година.')\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label class=\"control-label search-form2\" for=\"color\">Цвят</label> \r\n");
      out.write("\t\t\t\t<select id=\"color\" name=\"color\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t<option value=\"\">всички цветове</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Tъмно син\">Tъмно син</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Банан\">Банан</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Беата\">Беата</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Бежов\">Бежов</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Бордо\">Бордо</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Бронз\">Бронз</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Бял\">Бял</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Винен\">Винен</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Виолетов\">Виолетов</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Вишнев\">Вишнев</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Графит\">Графит</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Жълт\">Жълт</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Зелен\">Зелен</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Златист\">Златист</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Кафяв\">Кафяв</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Керемиден\">Керемиден</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Кремав\">Кремав</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Лилав\">Лилав</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Металик\">Металик</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Оранжев\">Оранжев</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Охра\">Охра</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Пепеляв\">Пепеляв</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Перла\">Перла</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Пясъчен\">Пясъчен</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Резидав\">Резидав</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Розов\">Розов</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Сахара\">Сахара</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Светло сив\">Светло сив</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Светло син\">Светло син</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Сив\">Сив</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Син\">Син</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Слонова кост\">Слонова кост</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Сребърен\">Сребърен</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Т.зелен\">Т.зелен</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Тъмно сив\">Тъмно сив</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Тъмно син мет.\">Тъмно син мет.</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Тъмно червен\">Тъмно червен</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Тютюн\">Тютюн</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Хамелеон\">Хамелеон</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Червен\">Червен</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Черен\">Черен</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4\" style=\"margin-top: 20px\">\r\n");
      out.write("\t\t\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t\t\t<label class=\"control-label\" for=\"subcategory\">Категория</label> \r\n");
      out.write("\t\t\t\t\t<select\tid=\"subcategory\" name=\"subcategory\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\trequired oninput = \"setCustomValidity('')\" oninvalid=\"setCustomValidity('Моля задайте категория.')\">\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row search-form\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\" for=\"region\">Регион</label> \r\n");
      out.write("\t\t\t\t\t\t<select id=\"region\" name=\"region\" class=\"form-control\" required\r\n");
      out.write("\t\t\t\t\t\t\toninvalid=\"setCustomValidity('Моля изберете регион.')\" oninput=\"setCustomValidity('')\">\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\" for=\"location\">Населено място</label>\r\n");
      out.write("\t\t\t\t\t\t<select id=\"location\" name=\"location\" class=\"form-control\" required\r\n");
      out.write("\t\t\t\t\t\t\toninvalid=\"setCustomValidity('Моля изберете населено място.')\" oninput=\"setCustomValidity('')\">\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"row search-form\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<label class=\"control-label\" for=\"validity\">Валидност на обявата</label> \r\n");
      out.write("\t\t\t\t\t\t<select id=\"validity\" name=\"validity\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"30\">30</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"60\">60</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"90\">90</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"search-form2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" class=\"btn btn-info btn-block\"\tform=\"publishForm\"\r\n");
      out.write("\t\t\t\t\tstyle=\"height: 50px;\"  value=\"Публикувай обявата\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container extras\"\r\n");
      out.write("\t\tstyle=\"border-bottom: 1px solid #ccc; padding-bottom: 25px\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label\" for=\"safety\">Безопасност</label> \r\n");
      out.write("\t\t\t\t<label class=\"checkbox\" for=\"safety1\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" name=\"safety\" id=\"safety1\" value=\"safety1\">\r\n");
      out.write("\t\t\t\t\t\tGPS система за проследяване\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety2\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety2\" value=\"safety2\">Автоматичен\r\n");
      out.write("\t\t\t\t\tконтрол на стабилността\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety3\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety3\" value=\"safety3\">Адаптивни\r\n");
      out.write("\t\t\t\t\tпредни светлини\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety4\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety4\" value=\"safety4\">Антиблокираща\r\n");
      out.write("\t\t\t\t\tсистема\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety5\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety5\" value=\"safety5\">Въздушни\r\n");
      out.write("\t\t\t\t\tвъзглавници - Задни\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety6\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety6\" value=\"safety6\">Въздушни\r\n");
      out.write("\t\t\t\t\tвъзглавници - Предни\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety7\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety7\" value=\"safety7\">Въздушни\r\n");
      out.write("\t\t\t\t\tвъзглавници - Странични\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety8\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety8\" value=\"safety8\">\r\n");
      out.write("\t\t\t\t\tЕл. разпределяне на спирачното усилие\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety9\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety9\" value=\"safety9\">Електронна\r\n");
      out.write("\t\t\t\t\tпрограма за стабилизиране\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety10\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety10\" value=\"safety10\">Контрол\r\n");
      out.write("\t\t\t\t\tна налягането на гумите\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety11\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety11\" value=\"safety11\">\r\n");
      out.write("\t\t\t\t\tПарктроник\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety12\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety12\" value=\"safety12\">Система\r\n");
      out.write("\t\t\t\t\tза динамична устойчивост\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety13\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety13\" value=\"safety13\">Система\r\n");
      out.write("\t\t\t\t\tза защита от пробуксуване\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety14\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety14\" value=\"safety14\">Система\r\n");
      out.write("\t\t\t\t\tза изсушаване на накладките\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety15\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety15\" value=\"safety15\">Система\r\n");
      out.write("\t\t\t\t\tза контрол на дистанцията\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"safety16\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"safety\" id=\"safety16\" value=\"safety16\">Система\r\n");
      out.write("\t\t\t\t\tза подпомагане на спирането\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label\" for=\"comfort\">Комфорт</label> <label\r\n");
      out.write("\t\t\t\t\tclass=\"checkbox\" for=\"comfort1\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\tname=\"comfort\" id=\"comfort1\" value=\"comfort1\">Auto Start\r\n");
      out.write("\t\t\t\t\tStop function\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort2\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort2\" value=\"comfort2\">Bluetooth\r\n");
      out.write("\t\t\t\t\t\\ handsfree система\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort3\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort3\" value=\"comfort3\">DVD,\r\n");
      out.write("\t\t\t\t\tTV\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort4\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort4\" value=\"comfort4\">Steptronic,\r\n");
      out.write("\t\t\t\t\tTiptronic\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort5\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort5\" value=\"comfort5\">\r\n");
      out.write("\t\t\t\t\tUSB, audio\\video, IN\\AUX изводи\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort6\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort6\" value=\"comfort6\">Адаптивно\r\n");
      out.write("\t\t\t\t\tвъздушно окачване\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort7\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort7\" value=\"comfort7\">Безключово\r\n");
      out.write("\t\t\t\t\tпалене\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort8\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort8\" value=\"comfort8\">Блокаж\r\n");
      out.write("\t\t\t\t\tна диференциала\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort9\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort9\" value=\"comfort9\">Бордкомпютър\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort10\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort10\" value=\"comfort10\">Датчик\r\n");
      out.write("\t\t\t\t\tза светлина\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort11\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort11\" value=\"comfort11\">\r\n");
      out.write("\t\t\t\t\tЕл. Огледала\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort12\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort12\" value=\"comfort12\">Ел.\r\n");
      out.write("\t\t\t\t\tСтъкла\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort13\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort13\" value=\"comfort13\">Ел.\r\n");
      out.write("\t\t\t\t\tрегулиране на окачването\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort14\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort14\" value=\"comfort14\">Ел.\r\n");
      out.write("\t\t\t\t\tрегулиране на седалките\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort15\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort15\" value=\"comfort15\">Ел.\r\n");
      out.write("\t\t\t\t\tусилвател на волана\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort16\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort16\" value=\"comfort16\">Климатик\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort17\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort17\" value=\"comfort17\">\r\n");
      out.write("\t\t\t\t\tКлиматроник\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort18\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort18\" value=\"comfort18\">\r\n");
      out.write("\t\t\t\t\tМултифункционален волан\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort19\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort19\" value=\"comfort19\">\r\n");
      out.write("\t\t\t\t\tНавигация\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort20\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort20\" value=\"comfort20\">Отопление\r\n");
      out.write("\t\t\t\t\tна волана\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort21\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort21\" value=\"comfort21\">Печка\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort22\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort22\" value=\"comfort22\">Подгряване\r\n");
      out.write("\t\t\t\t\tна предното стъкло\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort23\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort23\" value=\"comfort23\">Подгряване\r\n");
      out.write("\t\t\t\t\tна седалките\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort24\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort24\" value=\"comfort24\">Регулиране\r\n");
      out.write("\t\t\t\t\tна волана\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort25\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort25\" value=\"comfort25\">Сензор\r\n");
      out.write("\t\t\t\t\tза дъжд\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort26\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort26\" value=\"comfort26\">Серво\r\n");
      out.write("\t\t\t\t\tусилвател на волана\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort27\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort27\" value=\"comfort27\">Система\r\n");
      out.write("\t\t\t\t\tза измиване на фаровете\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort28\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort28\" value=\"comfort28\">Система\r\n");
      out.write("\t\t\t\t\tза контрол на скоростта(автопилот)\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort29\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort29\" value=\"comfort29\">Стерео\r\n");
      out.write("\t\t\t\t\tуредба\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort30\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort30\" value=\"comfort30\">Филтър\r\n");
      out.write("\t\t\t\t\tза твърди частици\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"comfort31\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"comfort\" id=\"comfort31\" value=\"comfort31\">Хладилна\r\n");
      out.write("\t\t\t\t\tжабка\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label\" for=\"other\"> Други </label> <label\r\n");
      out.write("\t\t\t\t\tclass=\"checkbox\" for=\"other1\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\tname=\"other1\" id=\"other1\" value=\"other1\">4x4\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other2\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other2\" value=\"other2\">7\r\n");
      out.write("\t\t\t\t\tместа\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other3\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other3\" value=\"other3\">Buy\r\n");
      out.write("\t\t\t\t\tback\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other4\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other4\" value=\"other4\">Бартер\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other5\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other5\" value=\"other5\">Газова\r\n");
      out.write("\t\t\t\t\tуредба\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other6\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other6\" value=\"other6\">Капариран\\Продаден\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other7\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other7\" value=\"other7\">Катастрофирал\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other8\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other8\" value=\"other8\">Лизинг\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other9\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other9\" value=\"other9\">Метанова\r\n");
      out.write("\t\t\t\t\tуредба\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other10\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other10\" value=\"other10\">На\r\n");
      out.write("\t\t\t\t\tчасти\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other11\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other11\" value=\"other11\">Напълно\r\n");
      out.write("\t\t\t\t\tобслужен\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other12\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other12\" value=\"other12\">Нов\r\n");
      out.write("\t\t\t\t\tвнос\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other13\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other13\" value=\"other13\">С\r\n");
      out.write("\t\t\t\t\tправо на дан.к-т\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other14\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other14\" value=\"other14\">С\r\n");
      out.write("\t\t\t\t\tрегистрация\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other15\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other15\" value=\"other15\">Сервизна\r\n");
      out.write("\t\t\t\t\tкнижка\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"other16\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"other\" id=\"other16\" value=\"other16\">Тунинг\r\n");
      out.write("\t\t\t\t</label> <label class=\"control-label\" for=\"exterior\">Екстериор</label> <label\r\n");
      out.write("\t\t\t\t\tclass=\"checkbox\" for=\"exterior1\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\tname=\"exterior\" id=\"exterior1\" value=\"exterior1\">2(3) Врати\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"exterior2\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"exterior\" id=\"exterior2\" value=\"exterior2\">4(5)\r\n");
      out.write("\t\t\t\t\tВрати\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"exterior3\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"exterior\" id=\"exterior3\" value=\"exterior3\">LED\r\n");
      out.write("\t\t\t\t\tфарове\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"exterior4\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"exterior\" id=\"exterior4\" value=\"exterior4\">Ксенонови\r\n");
      out.write("\t\t\t\t\tфарове\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"exterior5\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"exterior\" id=\"exterior5\" value=\"exterior5\">Лети\r\n");
      out.write("\t\t\t\t\tджанти\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"exterior6\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"exterior\" id=\"exterior6\" value=\"exterior6\">Металик\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"exterior7\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"exterior\" id=\"exterior7\" value=\"exterior7\">Отопляеми\r\n");
      out.write("\t\t\t\t\tчистачки\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"exterior8\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"exterior\" id=\"exterior8\" value=\"exterior8\">Панорамен\r\n");
      out.write("\t\t\t\t\tлюк\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"exterior9\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"exterior\" id=\"exterior9\" value=\"exterior9\">Спойлери\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"exterior10\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"exterior\" id=\"exterior10\" value=\"exterior10\">Теглич\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"exterior11\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"exterior\" id=\"exterior11\" value=\"exterior11\">Халогенни\r\n");
      out.write("\t\t\t\t\tфарове\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"exterior12\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"exterior\" id=\"exterior12\" value=\"exterior12\">Шибедах\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label\" for=\"security\">Защита</label> <label\r\n");
      out.write("\t\t\t\t\tclass=\"checkbox\" for=\"security1\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\tname=\"security\" id=\"security1\" value=\"security1\">Аларма\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"security2\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"security\" id=\"security2\" value=\"security2\">Брониран\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"security3\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"security\" id=\"security3\" value=\"security3\">Имобилайзер\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"security3\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"security\" id=\"security3\" value=\"security3\">Каско\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"security3\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"security\" id=\"security3\" value=\"security3\">Централно\r\n");
      out.write("\t\t\t\t\tзаключване\r\n");
      out.write("\t\t\t\t</label> <label class=\"control-label\" for=\"interior\">Интериор</label> <label\r\n");
      out.write("\t\t\t\t\tclass=\"checkbox\" for=\"interior1\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\tname=\"interior\" id=\"interior1\" value=\"interior1\">Велурен\r\n");
      out.write("\t\t\t\t\tсалон\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"interior2\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"interior\" id=\"interior2\" value=\"interior2\">Десен\r\n");
      out.write("\t\t\t\t\tволан\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"interior3\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"interior\" id=\"interior3\" value=\"interior3\">Кожен\r\n");
      out.write("\t\t\t\t\tсалон\r\n");
      out.write("\t\t\t\t</label> <label class=\"control-label\" for=\"special\">Специализирани</label> <label\r\n");
      out.write("\t\t\t\t\tclass=\"checkbox\" for=\"special1\"> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\tname=\"special\" id=\"special1\" value=\"special1\">TAXI\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"special2\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"special\" id=\"special2\" value=\"special2\">За\r\n");
      out.write("\t\t\t\t\tхора с увреждания\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"special3\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"special\" id=\"special3\" value=\"special3\">Катафалка\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"special4\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"special\" id=\"special4\" value=\"special4\">Линейка\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"special5\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"special\" id=\"special5\" value=\"special5\">Учебен\r\n");
      out.write("\t\t\t\t</label> <label class=\"checkbox\" for=\"special6\"> <input\r\n");
      out.write("\t\t\t\t\ttype=\"checkbox\" name=\"special\" id=\"special6\" value=\"special6\">Хладилен\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\" style=\"margin-bottom: 20px\">\r\n");
      out.write("\t\t<div class=\"row\" style=\"margin-top: -20px;\">\r\n");
      out.write("\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label\" for=\"info\">Допълнителна\r\n");
      out.write("\t\t\t\t\tинформация</label>\r\n");
      out.write("\t\t\t\t<textarea rows=\"10\" class=\"form-control\" name=\"info\" id=\"info\"></textarea>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t<h4 style=\"margin-top: 0px\">Данни за обратна връзка</h4>\r\n");
      out.write("\t\t\t\t<label class=\"control-label\" for=\"number\">Tелефон: </label> \r\n");
      out.write("\t\t\t\t\t<input id=\"number\" name=\"number\" type=\"text\" class=\"form-control input-md\" required required\r\n");
      out.write("\t\t\t\t\t\toninvalid=\"setCustomValidity('Моля въведете номер.')\" oninput=\"setCustomValidity('')\">\t\r\n");
      out.write("\t\t\t\t<label class=\"control-label\" for=\"email\">Email: </label> \r\n");
      out.write("\t\t\t\t\t<input id=\"email\" name=\"email\" type=\"email\" class=\"form-control input-md\" required\r\n");
      out.write("\t\t\t\t\t\toninvalid=\"setCustomValidity('Моля изберете регион.')\" oninput=\"setCustomValidity('')\">\r\n");
      out.write("\t\t\t\t<label class=\"control-label\" for=\"website\">Website: </label> \r\n");
      out.write("\t\t\t\t\t<input id=\"website\" name=\"website\" type=\"text\" class=\"form-control input-md\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("\t<div class=\"container footer-font\" style=>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>За нас</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"#\"> Условия за ползване</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"#\"> Поверителност</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"#\"> Контакти</a></p></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>Kонтакти</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p><i class=\"glyphicon glyphicon-map-marker\"></i> <strong>Адрес:</strong>\r\n");
      out.write("\t\t\t\t\t\tСофия 1404, бул. “България” №69, ет.14, Infinity Tower</p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><p><i class=\"glyphicon glyphicon-envelope\"></i> \r\n");
      out.write("\t\t\t\t\t\t<strong>Email:</strong>hakan.hyusen94@gmail.com</p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li><p><i class=\"glyphicon glyphicon-globe\"></i> \r\n");
      out.write("\t\t\t\t\t\t<strong>Website:</strong><a href=\"#\">www.jiguili.bg</a></p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>Друго</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p>\t&#x27a2; <a href=\"#\"> Форум</a></li>\r\n");
      out.write("\t\t\t\t\t<li><p> &#x27a2; <a href=\"#\"> FAQ's</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>\t&#x27a2; <a href=\"#\"> Помощ</a></p></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t<h4>Посетете също</h4>\r\n");
      out.write("\t\t\t\t<ul class=\"list-unstyled\">\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"http://automedia.investor.bg/\"> Automedia.bg</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"http://www.mobile.bg/\"> Mobile.bg</a></p></li>\r\n");
      out.write("\t\t\t\t\t<li><p>&#x27a2;<a href=\"http://www.topgear.bg/\"> Topgear.bg</a></p></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<p style=\"text-align: center;\">© Copyright 2016. All rights reserved.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<form action=\"Login\" method=\"POST\" class=\"row navbar-form navbar-left form-inline\" target=\"_blank\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" class=\"form-control\" id=\"email\" placeholder=\"Е-мейл\" required\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\toninvalid=\"this.setCustomValidity('Моля въведете валиден е-мейл.')\" oninput=\"setCustomValidity('')\"> \r\n");
        out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"pass\" id=\"pass\" class=\"form-control\" placeholder=\"Парола\" required\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\toninvalid=\"this.setCustomValidity('Моля въведете парола.')\" oninput=\"setCustomValidity('')\"> \r\n");
        out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" class=\"btn btn-success form-control\" value=\"Вход\">\r\n");
        out.write("\t\t\t\t\t\t\t\t</form>\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
